name: Docker

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare code
        run: |
          touch docker-compose.env
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> docker-compose.env
          echo "CODECOMMIT_HOST=${{ secrets.CODECOMMIT_HOST }}" >> docker-compose.env
          echo "CODECOMMIT_USER=${{ secrets.CODECOMMIT_USER }}" >> docker-compose.env
          echo "CODECOMMIT_PASSWORD=${{ secrets.CODECOMMIT_PASSWORD }}" >> docker-compose.env

      - name: Run tests
        run: |
          docker-compose -f docker-compose-56.yml up --build -d

          docker run -t --network php56 jwilder/dockerize -wait http://php56_nginx/ -timeout 120s

          docker ps -a

          docker logs php56_app

          CONTENT=$(curl -s "http://127.0.0.1/");
          echo "CHAMADA HTTP: ${CONTENT}";

          if [ "${CONTENT}" != "Like Sistemas|123|56" ]; then
            echo "Chamada HTTP retornou errado: ${CONTENT}"
            exit 1;
          fi

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: likesistemas/php
          dockerfile: Dockerfile-56
          tags: 56,5.6
